[project]
name = "pytuck-view"
version = "0.0.1"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "pydantic>=2.12.5",
    "pytuck[all]>=0.3.0",
    "uvicorn>=0.20.0",
    "jinja2>=3.0.0",
]
